// AUTO-GENERATED by `npm run generate:types`. Do not edit by hand.
// Flat aliases for every API Resource schema (e.g. `import type { User } from '@/types/api/schemas'`).

import type { components } from './index';

export type AuthConfig = components['schemas']['AuthConfig'];
export type ProfileSettings = components['schemas']['ProfileSettings'];
export type User = components['schemas']['User'];
